const ROLE_ADMIN = 6;
const ROLE_EMPLOYEE = 5;
const LOAI_KHACH_HANG = {
  KHACH_LE: 0,
  KHACH_DOAN: 1,
}
const LOAI_THUE_PHONG = {
  THEO_GIO: 0,
  THEO_NGAY: 1,
  QUA_DEM: 2,
}
const TRANG_THAI_PHIEU = {
  DAT_PHONG: 0,
  NHAN_PHONG: 1,
  TRA_PHONG: 2,
  DA_HUY: 3,
}
const TRANG_THAI_THANH_TOAN = {
  DA_THANH_TOAN: 0,
  CHUA_THANH_TOAN: 1,
  KY_GUI: 2,
}
const TRANG_THAI_PHONG = {
  KHA_DUNG: 0,
  DA_DAT_PHONG: 1,
  CHUA_DON_BUONG: 2,
  DANG_SUA_PHONG: 3,
  KHACH_DANG_O: 4,
};
const LOAI_PHIEU_THU = {
  CONG_NO: 0,
  TRA_TRUOC: 1,
}
module.exports = {
  ROLE_ADMIN,
  ROLE_EMPLOYEE,
  LOAI_THUE_PHONG,
  LOAI_KHACH_HANG,
  TRANG_THAI_PHIEU,
  TRANG_THAI_THANH_TOAN,
  TRANG_THAI_PHONG,
  LOAI_PHIEU_THU,
}